src/Entity/Vols.php
<?php

namespace App\Entity;

use App\Repository\VolsRepository;
use Cassandra\Date;
use Doctrine\ORM\Mapping as ORM;
use PhpParser\Node\Scalar\String_;
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Serializer\Annotation\Groups;
use Captcha\Bundle\CaptchaBundle\Validator\Constraints as CaptchaAssert;
use Symfony\Component\Form\Extension\Core\Type\FileType;



/**
 * @ORM\Entity(repositoryClass=VolsRepository::class)
 */
class Vols
{
    /** @var int
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     * @Groups("Vols")
     * @Groups("posts:read")
     */
    private $id;

    /**
     * @var string
     * Assert\NotBlank(message="destination doit etre non vide")
     * @Assert\Length(
     *     min = 5,
     *     minMessage=" destination doit être  au mini de 5 caracteres"
     * )
     * @ORM\Column(type="string", length=255)
     * @Groups("Vols")
     * @Groups("posts:read")
     */
    private $destination_aller;

    /**
     * @var string
     * Assert\NotBlank(message="destination doit etre non vide")
     * @Assert\Length(
     *     min = 5,
     *     minMessage=" destination doit être  au mini de 5 caracteres"
     * )
     * @ORM\Column(type="string", length=255)
     * @Groups("Vols")
     * @Groups("posts:read")
     */
    private $destination_retour;

    /**
     * @var string
     * Assert\NotBlank(message="voyage doit etre non vide")
     * @Assert\Length(
     *     min = 5,
     *     minMessage=" voyage doit être  au mini de 5 caracteres"
     * )
     * @ORM\Column(type="string", length=255)
     * @Groups("Vols")
     * @Groups("posts:read")
     */
    private $voyage;

    /**
     * @var Date
     * @Assert\DateTime
     * @var string A "Y-m-d H:i:s" formatted value
     * @ORM\Column(type="date")
     * @Groups("Vols")
     * @Groups("posts:read")
     */
    private $date_depart;

    /**
     * @var Date
     * @Assert\DateTime
     * @var string A "Y-m-d H:i:s" formatted value
     * @ORM\Column(type="date")
     * @Groups("Vols")
     * @Groups("posts:read")
     */
    private $date_retour;

    /**
     * @var String
     * Assert\NotBlank(message="passagers doit etre non vide")
     * @Assert\Length(
     *     min = 5,
     *     minMessage=" passagers doit être  au mini de 5 caracteres"
     * )
     * @ORM\Column(type="string", length=255)
     * @Groups("Vols")
     * @Groups("posts:read")
     */
    private $passagers;

    /**
     * @var string
     * Assert\NotBlank(message="cabine doit etre non vide")
     * @Assert\Length(
     *     min = 3,
     *     minMessage=" cabine doit être au mini de 3 caracteres"
     * )
     * @ORM\Column(type="string", length=255)
     * @Groups("Vols")
     * @Groups("posts:read")
     */
    private $cabine;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDestinationAller(): ?string
    {
        return $this->destination_aller;
    }

    public function setDestinationAller(string $destination_aller): self
    {
        $this->destination_aller = $destination_aller;

        return $this;
    }

    public function getDestinationRetour(): ?string
    {
        return $this->destination_retour;
    }

    public function setDestinationRetour(string $destination_retour): self
    {
        $this->destination_retour = $destination_retour;

        return $this;
    }

    public function getVoyage(): ?string
    {
        return $this->voyage;
    }

    public function setVoyage(string $voyage): self
    {
        $this->voyage = $voyage;

        return $this;
    }

    public function getDateDepart(): ?\DateTimeInterface
    {
        return $this->date_depart;
    }

    public function setDateDepart(\DateTimeInterface $date_depart): self
    {
        $this->date_depart = $date_depart;

        return $this;
    }

    public function getDateRetour(): ?\DateTimeInterface
    {
        return $this->date_retour;
    }

    public function setDateRetour(\DateTimeInterface $date_retour): self
    {
        $this->date_retour = $date_retour;

        return $this;
    }

    public function getPassagers(): ?string
    {
        return $this->passagers;
    }

    public function setPassagers(string $passagers): self
    {
        $this->passagers = $passagers;

        return $this;
    }

    public function getCabine(): ?string
    {
        return $this->cabine;
    }

    public function setCabine(string $cabine): self
    {
        $this->cabine = $cabine;

        return $this;
    }
}

src/Form/VolsType.php
<?php

namespace App\Form;

use App\Entity\Vols;
use phpDocumentor\Reflection\Types\String_;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class VolsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('destination_aller', TextType::class, [
                'attr' => [
                    'class' => 'form-control round-form'
                ]
            ])
            ->add('destination_retour', TextType::class, [
                'attr' => [
                    'class' => 'form-control round-form'
                ]
            ])
            ->add('voyage', TextType::class, [
                'attr' => [
                    'class' => 'form-control round-form'
                ]
            ])
            ->add('date_depart', DateType::class, [

                'widget' => 'single_text',
                'attr' => [
                    'class' => 'form-control round-form'
                ]
            ])
            ->add('date_retour', DateType::class, [

                'widget' => 'single_text',
                'attr' => [
                    'class' => 'form-control round-form'

                ]
            ])
            ->add('passagers', TextType::class, [
                'attr' => [
                    'class' => 'form-control round-form'
                ]
            ])
            ->add('cabine', TextType::class, [
                'attr' => [
                    'class' => 'form-control round-form'
                ]
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Vols::class,
        ]);
    }
}

src/Controller/VolsController.php
<?php

namespace App\Controller;

use App\Entity\Event;
use App\Entity\Vols;
use App\Form\VolsType;
use CMEN\GoogleChartsBundle\GoogleCharts\Charts\PieChart;
use App\Repository\VolsRepository;
//use phpDocumentor\Reflection\DocBlock\Serializer;
use phpDocumentor\Reflection\Types\Object_;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;
use Symfony\Component\Serializer\Encoder\JsonEncoder;
use DateTime ;
use Symfony\Component\Serializer\Normalizer\ObjectNormalizer;
use Symfony\Component\Serializer\Serializer;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Symfony\Component\Validator\Constraints\Json;

use Symfony\Component\Serializer\Encoder ;
class VolsController extends AbstractController
{



    /**
     * @Route("/search", name="search")
     */
      public function recherche(Request $request, VolsRepository $repo, PaginatorInterface $paginator) {

        

                  $searchForm = $this->createForm(VolsType::class);
                  $searchForm->handleRequest($request);

                  $donnees = $repo->findAll();

                  if ($searchForm->isSubmitted() && $searchForm->isValid()) {

                      $Destination_aller = $searchForm->getData()->getDestination_aller();

                      $donnees = $repo->search($Destination_aller);

                      if ($donnees == null) {
                          $this->addFlash('erreur', 'Aucun vols contenant ce mot clé dans le titre n\'a été trouvé, essayez en un autre.');
                      }

                  }

                  // Paginate the results of the query
                  $vol = $paginator->paginate(
                  // Doctrine Query, not results
                      $donnees,
                      // Define the page parameter
                      $request->query->getInt('page', 1),
                      // Items per page
                      4
                  );

                  return $this->render('vols/search.html.twig',[

                      'vols' => $vol,
                      'searchForm' => $searchForm->createView()
                  ]);
              }

          
  /**
 *
 * @Route("/", name="vols_index")
 */
    public function index2(Request $request): Response
    {

        // Retrieve the entity manager of Doctrine
        $data=$request->get('data');
        $em = $this->getDoctrine()->getManager();
        // Get some repository of data, in our case we have an vols entity
        $VolsRepository = $em->getRepository(Vols::class);

        // Find all the data on the vols table, filter your query as you need
        $vol = $VolsRepository->createQueryBuilder('vols')
            ->orWhere('Vols.name Like :name ')
            ->setParameter('voyage', '%'.$data.'%')
            ->getQuery();

        return $this->render('vols/index.html.twig', [
            'vols' => $vol,
        ]);
    } 



    /******************Ajouter vols*****************************************/
    /**
     * @Route("/addvolscode", name="add_volss")
     * @Method("POST")
     */

    public function ajoutervolsAction(Request $request)
    {
        $vols = new Vols();
        $destination_aller = $request->query->get("destination_aller");
        $destination_retour = $request->query->get("destination_retour");
        $voyage = $request->query->get("voyage");
        $em = $this->getDoctrine()->getManager();
        $date_depart = new \DateTime('now');
        $date_retour = new \DateTime('now');
        $passagers = $request->query->get("passagers");
        $cabine = $request->query->get("cabine");



        $vols->setDestinationAller($destination_aller);
        $vols->setDestinationRetour($destination_retour);
        $vols->setVoyage($voyage);
        $vols->setDateDepart($date_depart);
        $vols->setDateRetour($date_retour);
        $vols->setPassagers($passagers);
        $vols->setCabine($cabine);

        $em->persist($vols);
        $em->flush();
        $serializer = new Serializer([new ObjectNormalizer()]);
        $formatted = $serializer->normalize($vols);
        return new JsonResponse($formatted);

    }
    /******************Supprimer Reclamation*****************************************/

    /**
     * @Route("/deletevolscode", name="delete_volscode")
     * @Method("DELETE")
     */

    public function deletevolscode(Request $request) {
        $id = $request->get("id");

        $em = $this->getDoctrine()->getManager();
        $vols = $em->getRepository(Vols::class)->find($id);
        if($vols!=null ) {
            $em->remove($vols);
            $em->flush();

            $serialize = new Serializer([new ObjectNormalizer()]);
            $formatted = $serialize->normalize("vols a ete supprimee avec success.");
            return new JsonResponse($formatted);

        }
        return new JsonResponse("id vols invalide.");


    }
    /******************Modifier Reclamation*****************************************/
    /**
     * @Route("/updatevoldscode", name="update_volscode")
     * @Method("PUT")
     */
    public function modifiervolsAction(Request $request) {
        $em = $this->getDoctrine()->getManager();
        $vols = $this->getDoctrine()->getManager()
            ->getRepository(Vols::class)
            ->find($request->get("id"));

        $vols->setDestinationAller($request->get("destination_aller"));
        $vols->setDestinationRetour($request->get("destination_retour"));
        $vols->setVoyage($request->get("Voyage"));
        $vols->setPassagers($request->get("Passagers"));
        $vols->setCabine($request->get("Cabine"));

        $em->persist($vols);
        $em->flush();
        $serializer = new Serializer([new ObjectNormalizer()]);
        $formatted = $serializer->normalize($vols);
        return new JsonResponse("vols a ete modifiee avec success.");

    }

    /******************Detail vols*****************************************/

    /**
     * @Route("/detailvols", name="detail_vols")
     * @Method("GET")
     */

    //Detail vols
    public function detailvolsAction(Request $request)
    {
        $id = $request->get("id");

        $em = $this->getDoctrine()->getManager();
        $vols = $this->getDoctrine()->getManager()->getRepository(Vols::class)->find($id);
        $encoder = new JsonEncoder();
        $normalizer = new ObjectNormalizer();
        $normalizer->setCircularReferenceHandler(function ($object) {
            return $object->getDestination_aller();
        });
        $serializer = new Serializer([$normalizer], [$encoder]);
        $formatted = $serializer->normalize($vols);
        return new JsonResponse($formatted);
    }



    /**
     * @Route("/showcode", name="app_vols_showw")
     */
    public function showcode()
    {
        $vols =$this->getDoctrine()->getManager()->getRepository(vols::class)->findall() ;
        $serializer= new Serializer([new ObjectNormalizer()]) ;
        $formatted =$serializer->normalize($vols) ;
        return new JsonResponse($formatted) ;


    }

    /**
     * @Route("/", name="app_vols_index", methods={"GET"})
     */
    public function index(VolsRepository $volsRepository): Response
    {
        return $this->render('vols/index.html.twig', [
            'vols' => $volsRepository->findAll(),
        ]);
    }


    /**
     * @Route("/admin", name="display_admin", methods={"GET"})
     */
    public function indexadmin(): Response
    {
        return $this->render('admin/index.html.twig'
        );
    }


    /**
     * @Route("/new", name="app_vols_new", methods={"GET", "POST"})
     */
    public function new(Request $request, VolsRepository $volsRepository): Response
    {
        $vol = new Vols();
        $form = $this->createForm(VolsType::class, $vol);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $volsRepository->add($vol);
            return $this->redirectToRoute('app_vols_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('vols/new.html.twig', [
            'vol' => $vol,
            'form' => $form->createView(),
        ]);


    }


    /**
     * @Route("/show/{id}", name="app_vols_show", methods={"GET"})
     */
    public function show(Vols $vol): Response
    {
        return $this->render('vols/show.html.twig', [
            'vol' => $vol,
        ]);


    }



    /**
     * @Route("/showfront", name="app_vols_indexfront", methods={"GET"})
     */
    public function indexfront(VolsRepository $volsRepository): Response
    {
        return $this->render('vols/showfront.html.twig', [
            'vols' => $volsRepository->findAll(),
        ]);
    }

    /**
     * @Route("/edit/{id}", name="app_vols_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Vols $vol, VolsRepository $volsRepository): Response
    {
        $form = $this->createForm(VolsType::class, $vol);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em= $this->getDoctrine()->getManager()->flush();
            $volsRepository->add($vol);
            return $this->redirectToRoute('app_vols_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('vols/edit.html.twig', [
            'vol' => $vol,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/delete/{id}", name="app_vols_delete", methods={"POST"})
     */
    public function delete(Request $request, Vols $vol, VolsRepository $volsRepository): Response
    {

templates/vols/Callender.html.twig
{% extends 'base.back.html.twig' %}
{% block body %}
    <br>
    {% block title %}<center><h1>Vols Calendar</h1></center>{% endblock %}
    <br><br><br>
    <script src="https://cdn.jsdelivr.net/npm/fullcalendar@5.6.0/main.min.js" integrity="sha256-ekrJn2FeZaiUFq99QswpQCUTME/HxaDfX7R8INzKJGE=" crossorigin="anonymous"></script>

    <div id="calendrier">
        <script src="{{ asset('assets/js/fullcalendar.js') }}"></script>
    </div>

    {% block stylesheet %}
        <style>
            #calendrier{

                width: 600px;
                margin: auto;
                height:60%;
            }
        </style>

        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/fullcalendar@5.6.0/main.min.css" integrity="sha256-uq9PNlMzB+1h01Ij9cx7zeE2OR2pLAfRw3uUUOOPKdA=" crossorigin="anonymous">
    {% endblock %}

    {% block javascript %}
    <script>
        window.onload = () =>{
        let calendarElt=document.querySelector("#calendrier");
        let calendar =new FullCalendar.Calendar(calendarElt,{
        initialView: 'dayGridMonth',
        locale: 'fr',
        timeZone: 'Afrique/Tunisie',
        headerToolbar: {
        start: 'prev,next today',
        center: 'title',
        end: 'dayGridMonth'
    },
        events: {{data|raw}},
                //can edit
                editable: true,
                //can make it 2 days for example
                eventResizableFromStart: true
            });
            //get an object when you move an event
            calendar.on('eventChange', (e)=>{
                let url =`/api/${e.event.id}/edit`
                let donnees={
                    "destination_aller":e.event.extendedProps.destination_aller,
                    "destination_retour":e.event.extendedProps.destination_retour,
                    "title":e.event.title,
                    "start":e.event.start,
                    "date_retour":e.event.extendedProps.date_retour,
                    "passagers":e.event.extendedProps.passagers,
                    "cabine":e.event.extendedProps.cabine,
                }
                console.log(donnees);
                let xhr = new XMLHttpRequest()
                  xhr.open("PUT", url)

            xhr.setRequestHeader("X-Requested-With","XMLHttpRequest") ;
/* "X-Requested-With","XMLHttpRequest" */
                xhr.send(JSON.stringify(donnees))

            })
            calendar.render();
        }
    </script>
{% endblock %}{% endblock %}

templates/vols/_delete_form.html.twig
<form method="post" action="{{ path('app_vols_delete', {'id': vol.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ vol.id) }}">
    <button class="btn btn-round btn-danger btn-xs"><i class="fa fa-trash-o "></i></button>
</form>

templates/vols/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
<td><a href="{{ path('app_vols_index') }}">
    <button class="btn btn-round btn-success btn-xs">
        <i class="fa fa-check "></i></button> </a></td>
{{ form_end(form) }}

templates/vols/index.html.twig
{% extends 'base.back.html.twig' %}

{% block title %}Vols index{% endblock %}

{% block body %}
    <h1><font face="verdana" size="20px" color="#DD5526">Vols index</font></h1>
    <div id="divs">
        <input class="form-control" type="text" id="search" placeholder="🔍">
    </div>

    <table class="table" id="t" >
        <div class="row mt">
            <div class="col-md-12">

                    <table class="table table-striped table-advance table-hover">

                        <h4><i class="fa fa-angle-right"></i> Vols disponibles</h4>
                        <hr>
        <thead>

            <tr>

                <th><i class=" fa fa-edit"></i> Id</th>
                <th>Destination_aller</th>
                <th>Destination_retour</th>
                <th>Voyage</th>
                <th>Date_depart</th>
                <th>Date_retour</th>
                <th>Passagers</th>
                <th>Cabine</th>
                    <th>actions</th>
            </tr>

        </thead>

                        <tbody id="all">
        {% for vol in vols %}

            <tr>
                <td>{{ vol.id }}</td>
                <td>{{ vol.destinationAller}}</td>
                <td>{{ vol.destinationRetour }}</td>
                <td>{{ vol.voyage }}</td>
                <td>{{ vol.dateDepart ? vol.dateDepart|date('Y-m-d') : '' }}</td>
                <td>{{ vol.dateRetour ? vol.dateRetour|date('Y-m-d') : '' }}</td>
                <td>{{ vol.passagers }}</td>
                <td>{{ vol.cabine }}</td>
                <td>
                    <a href="{{ path('app_vols_show', {'id': vol.id}) }}">
                    <button type="button" class="btn btn-round btn-warning">afficher</button></a>


                    <a href="{{ path('app_vols_edit', {'id': vol.id}) }}">
                    <button class="btn btn-success btn-xs"><i class="fa fa-pencil"></i></button></a>
                </td>
              <td>  {{ include('vols/_delete_form.html.twig') }}</td>

            </tr>



        {% else %}
        <tr>
            <td colspan="9">no records found</td>
        </tr>
                        {% endfor %}
                        <tbody id="search">
                        </tbody>
                    </table>
                </tbody>
            </table>
            </div>
                <!-- /content-panel -->
            </div>
            <!-- /col-md-12 -->
        </div>



    <a href="{{ path('app_vols_new') }}">
        <button type="button" class="btn btn-round btn-info">ajouter</button></a>

    <a href="{{ path('search_vols')}}" class="btn btn-round btn-info">recherce avancé</a>
    </center>



{% endblock %}

templates/vols/index_tri.html.twig
{% extends 'base.front.html.twig' %}

{% block title %}Vols index{% endblock %}

{% block body %}
 <section class="inner_page_breadcrumb">
        <div class="container">
            <div class="row">
                <div class="col-xl-6 offset-xl-3 text-center">
                    <div class="breadcrumb_content">
                        <h4 class="breadcrumb_title">Vols</h4>
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Vols</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
    </section> 
    <form method="post" action="{{ path('testri') }}">

        <label>Ordre:
            <select class="form-control" name="type">
                <option>Croissant</option>
                <option>Décroissant</option>
            </select>
        </label>

        <label>Critère
            <select class="form-control" name="special">

                <option>date départ</option>
            </select>
        </label>
        <input type="submit" class="btn btn-style btn-primary" value="Trier">
    </form>
    <form method="post" action="{{ path('vols_index') }}">

        <h1><font face="verdana" size="20px" color="#DD5526">Vols index</font></h1>
        <label>Entrer Destionation aller</label>
        <label>
            <input type="text" name="data" class="form-control">
        </label><input type="submit" class="btn btn-style btn-primary" value="Recherche">

        <table class="table" id="t" >
            <div class="row mt">
                <div class="col-md-12">

                    <table class="table table-striped table-advance table-hover">

                        <h4><i class="fa fa-angle-right"></i> Vols disponibles</h4>
                        <hr>
                        <thead>

                        <tr>

                            <th><i class=" fa fa-edit"></i> Id</th>
                            <th>Destination_aller</th>
                            <th>Destination_retour</th>
                            <th>Voyage</th>
                            <th>Date_depart</th>
                            <th>Date_retour</th>
                            <th>Passagers</th>
                            <th>Cabine</th>
                            <th>actions</th>
                        </tr>

                        </thead>

                        <tbody id="all">
                        {% for vol in vols %}

                            <tr>
                                <td>{{ vol.id }}</td>
                                <td>{{ vol.destinationAller}}</td>
                                <td>{{ vol.destinationRetour }}</td>
                                <td>{{ vol.voyage }}</td>
                                <td>{{ vol.dateDepart ? vol.dateDepart|date('Y-m-d') : '' }}</td>
                                <td>{{ vol.dateRetour ? vol.dateRetour|date('Y-m-d') : '' }}</td>
                                <td>{{ vol.passagers }}</td>
                                <td>{{ vol.cabine }}</td>
                                <td>
                                    <a href="{{ path('app_vols_show', {'id': vol.id}) }}">
                                        <button type="button" class="btn btn-round btn-warning">afficher</button></a>
                                </td>


                            </tr>
                        {% else %}
                            <tr>
                                <td colspan="9">no records found</td>
                            </tr>
                        {% endfor %}
                        <tbody id="search">
                        </tbody>
                    </table>
                    </tbody>
        </table>
        </div>
        <!-- /content-panel -->
        </div>
        <!-- /col-md-12 -->
        </div>
        </div>




        <a href="{{ path('search_vols')}}" class="btn btn-round btn-info">recherce avancé</a>
        </center>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js">
        </script>
        <script>
            $( document ).ready(function() {

                /*begin rechercher avancee multicritéres selon sujet et staus*/
                $("#divs").keyup(function(e){
                    /* La variable value va prendre la valeur insérer dans le champ de texte afin d’effectuer la recherche */
                    var value = $("#search").val();
                    //    alert(value);
                    /* Ajax est lancé lors du remplissage du champ texte dont l’id est « search » pour faire la recherche */
                    $.ajax({
                        /* l’url est une chaine de caractères contenant l’adresse où la requête est envoyée */
                        url : "{{ path('search_recc') }}",
                        /* La méthode utilisée pour transférer les données est GET */
                        type : 'GET',
                        /*Ici search value va prendre la chaine entrée par un utilisateur dans la zone de recherche et sera placée après l’url */
                        data: {
                            'searchValue' : value,
                        },
                        /*Cette fonction permet de vider le contenu du tableau pour recevoir le nouveau contenu*/
                        success : function(retour){
                            if(retour){
                                $('#t tbody#search').empty();
                                $.each(JSON.parse(retour), function(i, obj) {
                                    $('#t tbody#all').hide();
                                    $('#t tbody#search').append(
                                        '<tr>' +
                                        '<td> '+obj.id +'  </td>' +
                                        '<td> '+obj.destinationAller +'  </td>' +
                                        '<td> '+obj.destinationRetour +'  </td>' +
                                        '<td> '+obj.voyage +'  </td>' +
                                        '<td> '+obj.dateDepart +'  </td>' +
                                        '<td> '+obj.dateRetour +'  </td>' +
                                        '<td> '+obj.passagers +'  </td>' +
                                        '<td> '+obj.cabine +'  </td>' +



                                        '<a href="{{ path('app_vols_show',{'id':'+obj.id+'}) }}">show</a>'+

                                        '<a href="{{ path('app_vols_edit',{'id':'+obj.id+'}) }}">edit</a>' +




                                        ' </tr>');
                                });
                            }
                            else
                            {

                                $('#t tbody#all').show();
                                $('#t tbody#search').empty();
                                $('#t tbody#search').fadeIn('fast');

                            }
                        },
                    });
                    return false;
                });
                /*end rechercher avancee multicritéres selon sujet et staus*/
            });
        </script>

    </form>

{% endblock %}

templates/vols/show.html.twig
{% extends 'base.back.html.twig' %}

{% block title %}les Vols ajoutés {% endblock %}

{% block body %}

    <h1> <font face="verdana" size="20px" color="#FF7A59">vols</font> </h1>


    <div class="adv-table">
    <table  cellpadding="0" cellspacing="0" border="0" class="display table table-bordered" id="hidden-table-info">

        <font face="verdana" size="20px" >
        <thead>
            <tr>
                <th>Id</th>
                <td class="hidden-phone">  {{ vol.id }}</td>
            </tr>
          <tr>
                <th>Destination_aller</th>
                <td>{{ vol.destinationAller }}</td>
            </tr>
            <tr>
                <th>Destination_retour</th>
                <td>{{ vol.destinationRetour }}</td>
            </tr>
            <tr>
                <th>Voyage</th>
                <td>{{ vol.voyage }}</td>
            </tr>
            <tr>
                <th>Date_depart</th>
                <td>{{ vol.dateDepart ? vol.dateDepart|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Date_retour</th>
                <td>{{ vol.dateRetour ? vol.dateRetour|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Passagers</th>
                <td>{{ vol.passagers }}</td>
            </tr>
            <tr>
                <th>Cabine</th>
                <td>{{ vol.cabine }}</td>

            </tr>
            </thead>



        <td>


        </td>
        </font> </tr>

    <tr>
     <td>
         <a href="{{ path('app_vols_edit', {'id': vol.id}) }}">
             <button class="btn btn-round btn-success btn-xs"><i class="fa fa-edit "></i></button> </a>
         </a>
     </td>
        <td>
            <a href="{{ path('app_vols_index') }}">
                <button class="btn btn-round btn-success btn-xs"><i class="fa fa-arrow-circle-left "></i></button> </a>

        </td>

        <td>
            {{ include('vols/_delete_form.html.twig') }}
        </td>

    </tr>



</table>
    </div>
    <!-- page end-->

{% endblock %}